name: deploy

on:
  workflow_run:
    workflows: [ "Laravel" ]
    types:
      - completed
    branches:
      - master

concurrency: production_environment

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
          cache: composer

      - name: Install dependencies
        run: composer install

      - name: Deploy
        uses: deployphp/action@v1
        env:
          DEPLOY_HOSTNAME: ${{ secrets.DEPLOY_HOSTNAME }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: deploy
