name: deploy

on:
  push:
    branches: [ master ]

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install dependencies
        run: composer install

      - name: Deploy
        uses: deployphp/action@v1
        env:
          DEPLOY_HOSTNAME: ${{ secrets.DEPLOY_HOSTNAME }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: deploy
